import { Employee, Department } from "@/types";

export const departments: Department[] = [
  { id: "1", name: "الهندسة", employeeCount: 5, manager: "أحمد المطيري" },
  { id: "2", name: "التسويق", employeeCount: 3, manager: "سارة القحطاني" },
  { id: "3", name: "المالية", employeeCount: 3, manager: "خالد العتيبي" },
  { id: "4", name: "العمليات", employeeCount: 3, manager: "فهد الشمري" },
  { id: "5", name: "الموارد البشرية", employeeCount: 2, manager: "نورة الدوسري" },
  { id: "6", name: "تقنية المعلومات", employeeCount: 3, manager: "عبدالله الحربي" },
  { id: "7", name: "المبيعات", employeeCount: 2, manager: "محمد الغامدي" },
  { id: "8", name: "خدمة العملاء", employeeCount: 2, manager: "ريم الزهراني" },
];

export const employees: Employee[] = [
  {
    id: "1",
    employeeId: "EMP-001",
    name: "أحمد المطيري",
    email: "ahmed@company.sa",
    phone: "0551234567",
    nationalId: "1098765432",
    dateOfBirth: "1990-03-15",
    gender: "ذكر",
    nationality: "سعودي",
    department: "الهندسة",
    position: "مدير الهندسة",
    joinDate: "2020-01-15",
    contractType: "دوام كامل",
    salary: 25000,
    status: "نشط",
    leaveBalance: 21,
    attendanceRate: 96,
  },
  {
    id: "2",
    employeeId: "EMP-002",
    name: "سارة القحطاني",
    email: "sara@company.sa",
    phone: "0559876543",
    nationalId: "1087654321",
    dateOfBirth: "1992-07-22",
    gender: "أنثى",
    nationality: "سعودية",
    department: "التسويق",
    position: "مديرة التسويق",
    joinDate: "2019-06-01",
    contractType: "دوام كامل",
    salary: 22000,
    status: "نشط",
    leaveBalance: 18,
    attendanceRate: 98,
  },
  {
    id: "3",
    employeeId: "EMP-003",
    name: "خالد العتيبي",
    email: "khaled@company.sa",
    phone: "0553456789",
    nationalId: "1076543210",
    dateOfBirth: "1988-11-08",
    gender: "ذكر",
    nationality: "سعودي",
    department: "المالية",
    position: "المدير المالي",
    joinDate: "2018-03-20",
    contractType: "دوام كامل",
    salary: 28000,
    status: "نشط",
    leaveBalance: 15,
    attendanceRate: 94,
  },
  {
    id: "4",
    employeeId: "EMP-004",
    name: "فهد الشمري",
    email: "fahad@company.sa",
    phone: "0554567890",
    nationalId: "1065432109",
    dateOfBirth: "1991-05-30",
    gender: "ذكر",
    nationality: "سعودي",
    department: "العمليات",
    position: "مدير العمليات",
    joinDate: "2021-02-10",
    contractType: "دوام كامل",
    salary: 24000,
    status: "نشط",
    leaveBalance: 22,
    attendanceRate: 97,
  },
  {
    id: "5",
    employeeId: "EMP-005",
    name: "نورة الدوسري",
    email: "noura@company.sa",
    phone: "0555678901",
    nationalId: "1054321098",
    dateOfBirth: "1993-09-12",
    gender: "أنثى",
    nationality: "سعودية",
    department: "الموارد البشرية",
    position: "مديرة الموارد البشرية",
    joinDate: "2020-08-15",
    contractType: "دوام كامل",
    salary: 23000,
    status: "إجازة",
    leaveBalance: 5,
    attendanceRate: 92,
  },
  {
    id: "6",
    employeeId: "EMP-006",
    name: "عبدالله الحربي",
    email: "abdullah@company.sa",
    phone: "0556789012",
    nationalId: "1043210987",
    dateOfBirth: "1989-12-25",
    gender: "ذكر",
    nationality: "سعودي",
    department: "تقنية المعلومات",
    position: "مدير تقنية المعلومات",
    joinDate: "2019-11-01",
    contractType: "دوام كامل",
    salary: 26000,
    status: "نشط",
    leaveBalance: 19,
    attendanceRate: 95,
  },
  {
    id: "7",
    employeeId: "EMP-007",
    name: "محمد الغامدي",
    email: "mohammed@company.sa",
    phone: "0557890123",
    nationalId: "1032109876",
    dateOfBirth: "1994-02-18",
    gender: "ذكر",
    nationality: "سعودي",
    department: "المبيعات",
    position: "مدير المبيعات",
    joinDate: "2021-05-20",
    contractType: "دوام كامل",
    salary: 21000,
    status: "نشط",
    leaveBalance: 24,
    attendanceRate: 93,
  },
  {
    id: "8",
    employeeId: "EMP-008",
    name: "ريم الزهراني",
    email: "reem@company.sa",
    phone: "0558901234",
    nationalId: "1021098765",
    dateOfBirth: "1995-06-14",
    gender: "أنثى",
    nationality: "سعودية",
    department: "خدمة العملاء",
    position: "مديرة خدمة العملاء",
    joinDate: "2022-01-10",
    contractType: "دوام كامل",
    salary: 20000,
    status: "نشط",
    leaveBalance: 26,
    attendanceRate: 99,
  },
  {
    id: "9",
    employeeId: "EMP-009",
    name: "يوسف السبيعي",
    email: "yousef@company.sa",
    phone: "0559012345",
    nationalId: "1010987654",
    dateOfBirth: "1996-04-03",
    gender: "ذكر",
    nationality: "سعودي",
    department: "الهندسة",
    position: "مهندس برمجيات أول",
    joinDate: "2021-09-15",
    contractType: "دوام كامل",
    salary: 18000,
    status: "نشط",
    leaveBalance: 20,
    attendanceRate: 96,
  },
  {
    id: "10",
    employeeId: "EMP-010",
    name: "لينا الراشد",
    email: "lina@company.sa",
    phone: "0550123456",
    nationalId: "1009876543",
    dateOfBirth: "1997-08-21",
    gender: "أنثى",
    nationality: "سعودية",
    department: "التسويق",
    position: "أخصائية تسويق رقمي",
    joinDate: "2022-03-01",
    contractType: "دوام كامل",
    salary: 14000,
    status: "نشط",
    leaveBalance: 25,
    attendanceRate: 97,
  },
  {
    id: "11",
    employeeId: "EMP-011",
    name: "عمر الجهني",
    email: "omar@company.sa",
    phone: "0551122334",
    nationalId: "1098712345",
    dateOfBirth: "1990-10-10",
    gender: "ذكر",
    nationality: "سعودي",
    department: "الهندسة",
    position: "مهندس برمجيات",
    joinDate: "2022-06-15",
    contractType: "دوام كامل",
    salary: 15000,
    status: "نشط",
    leaveBalance: 23,
    attendanceRate: 94,
  },
  {
    id: "12",
    employeeId: "EMP-012",
    name: "هند العنزي",
    email: "hind@company.sa",
    phone: "0552233445",
    nationalId: "1087612345",
    dateOfBirth: "1993-01-28",
    gender: "أنثى",
    nationality: "سعودية",
    department: "المالية",
    position: "محاسبة",
    joinDate: "2021-11-01",
    contractType: "دوام كامل",
    salary: 13000,
    status: "نشط",
    leaveBalance: 18,
    attendanceRate: 98,
  },
  {
    id: "13",
    employeeId: "EMP-013",
    name: "ماجد الحارثي",
    email: "majed@company.sa",
    phone: "0553344556",
    nationalId: "1076512345",
    dateOfBirth: "1987-07-05",
    gender: "ذكر",
    nationality: "سعودي",
    department: "العمليات",
    position: "مشرف عمليات",
    joinDate: "2020-04-20",
    contractType: "دوام كامل",
    salary: 16000,
    status: "منتهي العقد",
    leaveBalance: 0,
    attendanceRate: 88,
  },
  {
    id: "14",
    employeeId: "EMP-014",
    name: "دانة السلمي",
    email: "dana@company.sa",
    phone: "0554455667",
    nationalId: "1065412345",
    dateOfBirth: "1995-03-17",
    gender: "أنثى",
    nationality: "سعودية",
    department: "تقنية المعلومات",
    position: "مطورة واجهات",
    joinDate: "2023-01-15",
    contractType: "دوام كامل",
    salary: 14000,
    status: "نشط",
    leaveBalance: 28,
    attendanceRate: 96,
  },
  {
    id: "15",
    employeeId: "EMP-015",
    name: "سلطان المالكي",
    email: "sultan@company.sa",
    phone: "0555566778",
    nationalId: "1054312345",
    dateOfBirth: "1991-11-22",
    gender: "ذكر",
    nationality: "سعودي",
    department: "المبيعات",
    position: "مندوب مبيعات",
    joinDate: "2022-08-01",
    contractType: "دوام كامل",
    salary: 12000,
    status: "نشط",
    leaveBalance: 22,
    attendanceRate: 91,
  },
  {
    id: "16",
    employeeId: "EMP-016",
    name: "عائشة البلوي",
    email: "aisha@company.sa",
    phone: "0556677889",
    nationalId: "1043212345",
    dateOfBirth: "1994-06-09",
    gender: "أنثى",
    nationality: "سعودية",
    department: "خدمة العملاء",
    position: "ممثلة خدمة عملاء",
    joinDate: "2023-03-10",
    contractType: "دوام كامل",
    salary: 10000,
    status: "نشط",
    leaveBalance: 28,
    attendanceRate: 95,
  },
  {
    id: "17",
    employeeId: "EMP-017",
    name: "تركي الوادعي",
    email: "turki@company.sa",
    phone: "0557788990",
    nationalId: "1032112345",
    dateOfBirth: "1992-09-01",
    gender: "ذكر",
    nationality: "سعودي",
    department: "الهندسة",
    position: "مهندس DevOps",
    joinDate: "2021-07-20",
    contractType: "دوام كامل",
    salary: 17000,
    status: "إجازة",
    leaveBalance: 3,
    attendanceRate: 93,
  },
  {
    id: "18",
    employeeId: "EMP-018",
    name: "مشاعل القرني",
    email: "mashael@company.sa",
    phone: "0558899001",
    nationalId: "1021012345",
    dateOfBirth: "1996-12-30",
    gender: "أنثى",
    nationality: "سعودية",
    department: "التسويق",
    position: "مصممة جرافيك",
    joinDate: "2022-10-05",
    contractType: "عقد مؤقت",
    salary: 11000,
    status: "نشط",
    leaveBalance: 15,
    attendanceRate: 97,
  },
  {
    id: "19",
    employeeId: "EMP-019",
    name: "بندر الشهري",
    email: "bandar@company.sa",
    phone: "0559900112",
    nationalId: "1010912345",
    dateOfBirth: "1989-04-14",
    gender: "ذكر",
    nationality: "سعودي",
    department: "المالية",
    position: "محلل مالي",
    joinDate: "2020-12-01",
    contractType: "دوام كامل",
    salary: 16000,
    status: "نشط",
    leaveBalance: 17,
    attendanceRate: 95,
  },
  {
    id: "20",
    employeeId: "EMP-020",
    name: "وفاء المري",
    email: "wafa@company.sa",
    phone: "0550011223",
    nationalId: "1009812345",
    dateOfBirth: "1998-02-07",
    gender: "أنثى",
    nationality: "سعودية",
    department: "الموارد البشرية",
    position: "أخصائية توظيف",
    joinDate: "2023-05-15",
    contractType: "دوام كامل",
    salary: 12000,
    status: "نشط",
    leaveBalance: 28,
    attendanceRate: 99,
  },
  {
    id: "21",
    employeeId: "EMP-021",
    name: "راكان العمري",
    email: "rakan@company.sa",
    phone: "0551133557",
    nationalId: "1098123456",
    dateOfBirth: "1993-08-19",
    gender: "ذكر",
    nationality: "سعودي",
    department: "تقنية المعلومات",
    position: "مدير أنظمة",
    joinDate: "2021-04-01",
    contractType: "دوام كامل",
    salary: 18000,
    status: "نشط",
    leaveBalance: 20,
    attendanceRate: 94,
  },
  {
    id: "22",
    employeeId: "EMP-022",
    name: "جمان الخالدي",
    email: "juman@company.sa",
    phone: "0552244668",
    nationalId: "1087123456",
    dateOfBirth: "1997-05-25",
    gender: "أنثى",
    nationality: "سعودية",
    department: "العمليات",
    position: "منسقة عمليات",
    joinDate: "2023-02-20",
    contractType: "دوام جزئي",
    salary: 8000,
    status: "نشط",
    leaveBalance: 14,
    attendanceRate: 96,
  },
  {
    id: "23",
    employeeId: "EMP-023",
    name: "عبدالرحمن الفيفي",
    email: "abdulrahman@company.sa",
    phone: "0553355779",
    nationalId: "1076123456",
    dateOfBirth: "1988-01-11",
    gender: "ذكر",
    nationality: "سعودي",
    department: "الهندسة",
    position: "مهندس بيانات",
    joinDate: "2020-09-10",
    contractType: "دوام كامل",
    salary: 19000,
    status: "نشط",
    leaveBalance: 16,
    attendanceRate: 92,
  },
];

export function getEmployeeById(id: string): Employee | undefined {
  return employees.find((e) => e.id === id);
}

export function getEmployeesByDepartment(department: string): Employee[] {
  return employees.filter((e) => e.department === department);
}

export function getActiveEmployeesCount(): number {
  return employees.filter((e) => e.status === "نشط").length;
}

export function getAverageAttendanceRate(): number {
  const active = employees.filter((e) => e.status === "نشط");
  return Math.round(
    active.reduce((sum, e) => sum + e.attendanceRate, 0) / active.length
  );
}

export function getTotalPayroll(): number {
  return employees
    .filter((e) => e.status === "نشط")
    .reduce((sum, e) => sum + e.salary, 0);
}
